esphome:
  name: ac_sala
  platform: ESP8266
  board: d1_mini
  includes:
    - Haier.h

logger:
  level: DEBUG
  # It is better to set baud_rate to 0, otherwise
  # ESP will perform painfully slow
  baud_rate: 0

wifi:
  ssid: !secret wifi-ssid
  password: !secret wifi-password

# Enable Home Assistant API
api:

ota:


climate:
  - platform: custom
    lambda: |-
      auto haier = new Haier();
      App.register_component(haier);
      return {haier};
    climates:
      - name: "ac sala"