esphome:
  name: haier_ac
  platform: ESP8266
  board: d1_mini
  includes:
    - src/constants.h
    - src/utility.h
    - src/utility.cpp
    - src/status.h
    - src/status.cpp
    - src/initialization.h
    - src/initialization.cpp
    - src/control.h
    - src/control.cpp
    - haier.h
    - haier.cpp

logger:
  level: DEBUG
  # It is better to set baud_rate to 0, otherwise
  # ESP will perform painfully slow
  baud_rate: 0

wifi:
  ssid: !secret wifi-ssid
  password: !secret wifi-password
  manual_ip:
    static_ip: !secret ip-address
    gateway: !secret ip-gateway
    subnet: !secret ip-subnet

# Enable Home Assistant API
api:

ota:


climate:
  - platform: custom
    lambda: |-
      auto haier = new Haier();
      App.register_component(haier);
      return {haier};
    climates:
      - name: "haier_ac"